// Code generated by protoc-gen-go.
// source: messages/messages.proto
// DO NOT EDIT!

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	messages/messages.proto

It has these top-level messages:
	Init
	InitResponse
	Ping
	MsgType
	Command
	CommandResult
	CommandPush
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgType_Types int32

const (
	MsgType_CommandResult MsgType_Types = 0
	MsgType_CommandPush   MsgType_Types = 1
)

var MsgType_Types_name = map[int32]string{
	0: "CommandResult",
	1: "CommandPush",
}
var MsgType_Types_value = map[string]int32{
	"CommandResult": 0,
	"CommandPush":   1,
}

func (x MsgType_Types) String() string {
	return proto.EnumName(MsgType_Types_name, int32(x))
}
func (MsgType_Types) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type Init struct {
	Version  int32  `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Magic    int32  `protobuf:"varint,2,opt,name=magic" json:"magic,omitempty"`
	App      string `protobuf:"bytes,3,opt,name=app" json:"app,omitempty"`
	Port     int32  `protobuf:"varint,4,opt,name=port" json:"port,omitempty"`
	Compress bool   `protobuf:"varint,5,opt,name=compress" json:"compress,omitempty"`
}

func (m *Init) Reset()                    { *m = Init{} }
func (m *Init) String() string            { return proto.CompactTextString(m) }
func (*Init) ProtoMessage()               {}
func (*Init) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Init) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Init) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *Init) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *Init) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Init) GetCompress() bool {
	if m != nil {
		return m.Compress
	}
	return false
}

type InitResponse struct {
	Magic   int32 `protobuf:"varint,1,opt,name=magic" json:"magic,omitempty"`
	Allowed bool  `protobuf:"varint,2,opt,name=allowed" json:"allowed,omitempty"`
}

func (m *InitResponse) Reset()                    { *m = InitResponse{} }
func (m *InitResponse) String() string            { return proto.CompactTextString(m) }
func (*InitResponse) ProtoMessage()               {}
func (*InitResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InitResponse) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *InitResponse) GetAllowed() bool {
	if m != nil {
		return m.Allowed
	}
	return false
}

type Ping struct {
	Version int32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Magic   int32 `protobuf:"varint,2,opt,name=magic" json:"magic,omitempty"`
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Ping) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Ping) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

type MsgType struct {
	Magic   int32         `protobuf:"varint,1,opt,name=magic" json:"magic,omitempty"`
	Msgtype MsgType_Types `protobuf:"varint,2,opt,name=msgtype,enum=messages.MsgType_Types" json:"msgtype,omitempty"`
}

func (m *MsgType) Reset()                    { *m = MsgType{} }
func (m *MsgType) String() string            { return proto.CompactTextString(m) }
func (*MsgType) ProtoMessage()               {}
func (*MsgType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MsgType) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *MsgType) GetMsgtype() MsgType_Types {
	if m != nil {
		return m.Msgtype
	}
	return MsgType_CommandResult
}

type Command struct {
	Magic     int32  `protobuf:"varint,1,opt,name=magic" json:"magic,omitempty"`
	Command   int32  `protobuf:"varint,2,opt,name=command" json:"command,omitempty"`
	Argstring string `protobuf:"bytes,3,opt,name=argstring" json:"argstring,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Command) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *Command) GetCommand() int32 {
	if m != nil {
		return m.Command
	}
	return 0
}

func (m *Command) GetArgstring() string {
	if m != nil {
		return m.Argstring
	}
	return ""
}

type CommandResult struct {
	Magic         int32  `protobuf:"varint,1,opt,name=magic" json:"magic,omitempty"`
	CommandResult int32  `protobuf:"varint,2,opt,name=commandResult" json:"commandResult,omitempty"`
	DisplayText   string `protobuf:"bytes,3,opt,name=displayText" json:"displayText,omitempty"`
}

func (m *CommandResult) Reset()                    { *m = CommandResult{} }
func (m *CommandResult) String() string            { return proto.CompactTextString(m) }
func (*CommandResult) ProtoMessage()               {}
func (*CommandResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CommandResult) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *CommandResult) GetCommandResult() int32 {
	if m != nil {
		return m.CommandResult
	}
	return 0
}

func (m *CommandResult) GetDisplayText() string {
	if m != nil {
		return m.DisplayText
	}
	return ""
}

type CommandPush struct {
	Magic    int32            `protobuf:"varint,1,opt,name=magic" json:"magic,omitempty"`
	Commands map[string]int32 `protobuf:"bytes,2,rep,name=commands" json:"commands,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *CommandPush) Reset()                    { *m = CommandPush{} }
func (m *CommandPush) String() string            { return proto.CompactTextString(m) }
func (*CommandPush) ProtoMessage()               {}
func (*CommandPush) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CommandPush) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *CommandPush) GetCommands() map[string]int32 {
	if m != nil {
		return m.Commands
	}
	return nil
}

func init() {
	proto.RegisterType((*Init)(nil), "messages.Init")
	proto.RegisterType((*InitResponse)(nil), "messages.InitResponse")
	proto.RegisterType((*Ping)(nil), "messages.Ping")
	proto.RegisterType((*MsgType)(nil), "messages.MsgType")
	proto.RegisterType((*Command)(nil), "messages.Command")
	proto.RegisterType((*CommandResult)(nil), "messages.CommandResult")
	proto.RegisterType((*CommandPush)(nil), "messages.CommandPush")
	proto.RegisterEnum("messages.MsgType_Types", MsgType_Types_name, MsgType_Types_value)
}

func init() { proto.RegisterFile("messages/messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0xab, 0xd3, 0x40,
	0x10, 0xc6, 0xdd, 0x36, 0x31, 0xe9, 0xd4, 0xa7, 0x75, 0x11, 0xde, 0xf2, 0xf0, 0x10, 0x56, 0x0f,
	0x01, 0xa1, 0x62, 0x05, 0x11, 0x05, 0x3d, 0x88, 0x07, 0x0f, 0x42, 0x59, 0x0a, 0x9e, 0xd7, 0x74,
	0x89, 0xc1, 0x24, 0xbb, 0x64, 0xb6, 0xb5, 0x39, 0xf9, 0xb7, 0xf8, 0x9f, 0x4a, 0xb6, 0xd9, 0x34,
	0x15, 0x72, 0xf0, 0x12, 0xe6, 0xfb, 0xf2, 0x4d, 0x7e, 0xbb, 0x93, 0x81, 0xdb, 0x4a, 0x21, 0xca,
	0x5c, 0xe1, 0x4b, 0x5f, 0xac, 0x4d, 0xa3, 0xad, 0xa6, 0xb1, 0xd7, 0xfc, 0x04, 0xc1, 0x97, 0xba,
	0xb0, 0x94, 0x41, 0x74, 0x54, 0x0d, 0x16, 0xba, 0x66, 0x24, 0x21, 0x69, 0x28, 0xbc, 0xa4, 0x4f,
	0x20, 0xac, 0x64, 0x5e, 0x64, 0x6c, 0xe6, 0xfc, 0xb3, 0xa0, 0x2b, 0x98, 0x4b, 0x63, 0xd8, 0x3c,
	0x21, 0xe9, 0x42, 0x74, 0x25, 0xa5, 0x10, 0x18, 0xdd, 0x58, 0x16, 0xb8, 0x98, 0xab, 0xe9, 0x1d,
	0xc4, 0x99, 0xae, 0x4c, 0xa3, 0x10, 0x59, 0x98, 0x90, 0x34, 0x16, 0x83, 0xe6, 0x1f, 0xe0, 0x41,
	0x47, 0x16, 0x0a, 0x8d, 0xae, 0x51, 0x5d, 0x38, 0x64, 0xcc, 0x61, 0x10, 0xc9, 0xb2, 0xd4, 0xbf,
	0xd4, 0xde, 0xf1, 0x63, 0xe1, 0x25, 0x7f, 0x03, 0xc1, 0xb6, 0xa8, 0xf3, 0xff, 0x3d, 0x39, 0xff,
	0x0d, 0xd1, 0x57, 0xcc, 0x77, 0xad, 0x99, 0x42, 0xbe, 0x82, 0xa8, 0xc2, 0xdc, 0xb6, 0x46, 0xb9,
	0xc6, 0x87, 0x9b, 0xdb, 0xf5, 0x30, 0xbe, 0xbe, 0x73, 0xdd, 0x3d, 0x50, 0xf8, 0x1c, 0x7f, 0x01,
	0xa1, 0x73, 0xe8, 0x63, 0xb8, 0xf9, 0xa4, 0xab, 0x4a, 0xd6, 0x7b, 0xa1, 0xf0, 0x50, 0xda, 0xd5,
	0x3d, 0xfa, 0x08, 0x96, 0xbd, 0xb5, 0x3d, 0xe0, 0x8f, 0x15, 0xe1, 0xdf, 0x20, 0xea, 0x8d, 0xe9,
	0x3b, 0x67, 0xe7, 0x40, 0x7f, 0x72, 0x2f, 0xe9, 0x53, 0x58, 0xc8, 0x26, 0x47, 0xdb, 0x14, 0x75,
	0xde, 0xcf, 0xfe, 0x62, 0xf0, 0xea, 0x1f, 0xf8, 0xc4, 0xe7, 0x9f, 0xc3, 0x4d, 0x36, 0x8e, 0xf5,
	0x90, 0x6b, 0x93, 0x26, 0xb0, 0xdc, 0x17, 0x68, 0x4a, 0xd9, 0xee, 0xd4, 0xc9, 0xf6, 0xb0, 0xb1,
	0xc5, 0xff, 0x90, 0xab, 0x9b, 0x4d, 0xd0, 0x3e, 0xba, 0x15, 0xe8, 0x42, 0xc8, 0x66, 0xc9, 0x3c,
	0x5d, 0x6e, 0x9e, 0x5d, 0xc6, 0x39, 0x6a, 0xf7, 0x35, 0x7e, 0xae, 0x6d, 0xd3, 0x8a, 0xa1, 0xe9,
	0xee, 0xfd, 0x70, 0xab, 0xf3, 0xab, 0x6e, 0xf5, 0x7e, 0xaa, 0xd6, 0x51, 0x16, 0xa2, 0x2b, 0x3b,
	0xf2, 0x51, 0x96, 0x07, 0xe5, 0x7f, 0xb4, 0x13, 0xef, 0x66, 0x6f, 0xc9, 0xf7, 0xfb, 0x6e, 0xdf,
	0x5f, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x18, 0xfd, 0xa8, 0x0a, 0x03, 0x00, 0x00,
}
