// Code generated by protoc-gen-go.
// source: src/messages/messages.proto
// DO NOT EDIT!

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	src/messages/messages.proto

It has these top-level messages:
	Init
	InitResponse
	Ping
	MsgType
	Command
	CommandResult
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgType_Types int32

const (
	MsgType_CommandResult MsgType_Types = 0
	MsgType_CommandPush   MsgType_Types = 1
)

var MsgType_Types_name = map[int32]string{
	0: "CommandResult",
	1: "CommandPush",
}
var MsgType_Types_value = map[string]int32{
	"CommandResult": 0,
	"CommandPush":   1,
}

func (x MsgType_Types) String() string {
	return proto.EnumName(MsgType_Types_name, int32(x))
}
func (MsgType_Types) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type Init struct {
	Version int32  `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Magic   int32  `protobuf:"varint,2,opt,name=magic" json:"magic,omitempty"`
	App     string `protobuf:"bytes,3,opt,name=app" json:"app,omitempty"`
	Port    int32  `protobuf:"varint,4,opt,name=port" json:"port,omitempty"`
}

func (m *Init) Reset()                    { *m = Init{} }
func (m *Init) String() string            { return proto.CompactTextString(m) }
func (*Init) ProtoMessage()               {}
func (*Init) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Init) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Init) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *Init) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *Init) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type InitResponse struct {
	Magic   int32 `protobuf:"varint,1,opt,name=magic" json:"magic,omitempty"`
	Allowed bool  `protobuf:"varint,2,opt,name=allowed" json:"allowed,omitempty"`
}

func (m *InitResponse) Reset()                    { *m = InitResponse{} }
func (m *InitResponse) String() string            { return proto.CompactTextString(m) }
func (*InitResponse) ProtoMessage()               {}
func (*InitResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InitResponse) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *InitResponse) GetAllowed() bool {
	if m != nil {
		return m.Allowed
	}
	return false
}

type Ping struct {
	Version int32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Magic   int32 `protobuf:"varint,2,opt,name=magic" json:"magic,omitempty"`
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Ping) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Ping) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

type MsgType struct {
	Magic   int32         `protobuf:"varint,1,opt,name=magic" json:"magic,omitempty"`
	Msgtype MsgType_Types `protobuf:"varint,2,opt,name=msgtype,enum=messages.MsgType_Types" json:"msgtype,omitempty"`
}

func (m *MsgType) Reset()                    { *m = MsgType{} }
func (m *MsgType) String() string            { return proto.CompactTextString(m) }
func (*MsgType) ProtoMessage()               {}
func (*MsgType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MsgType) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *MsgType) GetMsgtype() MsgType_Types {
	if m != nil {
		return m.Msgtype
	}
	return MsgType_CommandResult
}

type Command struct {
	Magic     int32  `protobuf:"varint,1,opt,name=magic" json:"magic,omitempty"`
	Command   int32  `protobuf:"varint,2,opt,name=command" json:"command,omitempty"`
	Argstring string `protobuf:"bytes,3,opt,name=argstring" json:"argstring,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Command) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *Command) GetCommand() int32 {
	if m != nil {
		return m.Command
	}
	return 0
}

func (m *Command) GetArgstring() string {
	if m != nil {
		return m.Argstring
	}
	return ""
}

type CommandResult struct {
	Magic         int32  `protobuf:"varint,1,opt,name=magic" json:"magic,omitempty"`
	CommandResult int32  `protobuf:"varint,2,opt,name=commandResult" json:"commandResult,omitempty"`
	DisplayText   string `protobuf:"bytes,3,opt,name=displayText" json:"displayText,omitempty"`
}

func (m *CommandResult) Reset()                    { *m = CommandResult{} }
func (m *CommandResult) String() string            { return proto.CompactTextString(m) }
func (*CommandResult) ProtoMessage()               {}
func (*CommandResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CommandResult) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *CommandResult) GetCommandResult() int32 {
	if m != nil {
		return m.CommandResult
	}
	return 0
}

func (m *CommandResult) GetDisplayText() string {
	if m != nil {
		return m.DisplayText
	}
	return ""
}

func init() {
	proto.RegisterType((*Init)(nil), "messages.Init")
	proto.RegisterType((*InitResponse)(nil), "messages.InitResponse")
	proto.RegisterType((*Ping)(nil), "messages.Ping")
	proto.RegisterType((*MsgType)(nil), "messages.MsgType")
	proto.RegisterType((*Command)(nil), "messages.Command")
	proto.RegisterType((*CommandResult)(nil), "messages.CommandResult")
	proto.RegisterEnum("messages.MsgType_Types", MsgType_Types_name, MsgType_Types_value)
}

func init() { proto.RegisterFile("src/messages/messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0x5d, 0xbb, 0x75, 0xdb, 0xa9, 0xd5, 0x1a, 0x04, 0x17, 0xf4, 0x50, 0x82, 0x87, 0x82,
	0x50, 0x51, 0xc1, 0xa3, 0x17, 0x4f, 0x1e, 0x84, 0x12, 0x0a, 0x5e, 0xbc, 0xc4, 0x6d, 0x88, 0x81,
	0xcd, 0x1f, 0x32, 0xa9, 0xda, 0x93, 0x5f, 0x5d, 0x9a, 0x66, 0xdb, 0x2a, 0xf4, 0xe0, 0x65, 0x99,
	0xf7, 0xe3, 0xe5, 0xbd, 0xec, 0x10, 0x38, 0x47, 0x5f, 0x5d, 0x6b, 0x81, 0xc8, 0xa5, 0xc0, 0xf5,
	0x30, 0x76, 0xde, 0x06, 0x4b, 0x3a, 0x8d, 0xa6, 0xaf, 0x90, 0x3f, 0x19, 0x15, 0x48, 0x09, 0xc5,
	0x87, 0xf0, 0xa8, 0xac, 0x29, 0xb3, 0x61, 0x36, 0x6a, 0xb3, 0x46, 0x92, 0x53, 0x68, 0x6b, 0x2e,
	0x55, 0x55, 0xee, 0x47, 0xbe, 0x12, 0x64, 0x00, 0x2d, 0xee, 0x5c, 0xd9, 0x1a, 0x66, 0xa3, 0x2e,
	0x5b, 0x8e, 0x84, 0x40, 0xee, 0xac, 0x0f, 0x65, 0x1e, 0x6d, 0x71, 0xa6, 0x0f, 0x70, 0xb8, 0x4c,
	0x67, 0x02, 0x9d, 0x35, 0x28, 0x36, 0x59, 0xd9, 0x76, 0x56, 0x09, 0x05, 0xaf, 0x6b, 0xfb, 0x29,
	0x66, 0xb1, 0xa3, 0xc3, 0x1a, 0x49, 0xef, 0x21, 0x9f, 0x28, 0x23, 0xff, 0x7b, 0x3b, 0xfa, 0x0d,
	0xc5, 0x33, 0xca, 0xe9, 0xc2, 0xed, 0xaa, 0xbc, 0x81, 0x42, 0xa3, 0x0c, 0x0b, 0x27, 0xe2, 0xc1,
	0xa3, 0xdb, 0xb3, 0xf1, 0x7a, 0x45, 0xe9, 0xe4, 0x78, 0xf9, 0x41, 0xd6, 0xf8, 0xe8, 0x15, 0xb4,
	0x23, 0x21, 0x27, 0xd0, 0x7f, 0xb4, 0x5a, 0x73, 0x33, 0x63, 0x02, 0xe7, 0x75, 0x18, 0xec, 0x91,
	0x63, 0xe8, 0x25, 0x34, 0x99, 0xe3, 0xfb, 0x20, 0xa3, 0x2f, 0x50, 0x24, 0xb0, 0xfb, 0x9f, 0xab,
	0x95, 0x21, 0xdd, 0xbc, 0x91, 0xe4, 0x02, 0xba, 0xdc, 0x4b, 0x0c, 0x5e, 0x19, 0x99, 0xf6, 0xbb,
	0x01, 0x54, 0xff, 0x29, 0xdf, 0x11, 0x7f, 0x09, 0xfd, 0x6a, 0xdb, 0x96, 0x4a, 0x7e, 0x43, 0x32,
	0x84, 0xde, 0x4c, 0xa1, 0xab, 0xf9, 0x62, 0x2a, 0xbe, 0x42, 0x2a, 0xdb, 0x46, 0x6f, 0x07, 0xf1,
	0xbd, 0xdc, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x83, 0xe2, 0x23, 0x4e, 0x02, 0x00, 0x00,
}
