// Code generated by protoc-gen-go.
// source: messages/messages.proto
// DO NOT EDIT!

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	messages/messages.proto

It has these top-level messages:
	Init
	InitResponse
	Ping
	Command
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Init struct {
	Version int32  `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Magic   int32  `protobuf:"varint,2,opt,name=magic" json:"magic,omitempty"`
	App     string `protobuf:"bytes,3,opt,name=app" json:"app,omitempty"`
}

func (m *Init) Reset()                    { *m = Init{} }
func (m *Init) String() string            { return proto.CompactTextString(m) }
func (*Init) ProtoMessage()               {}
func (*Init) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Init) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Init) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *Init) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

type InitResponse struct {
	Magic   int32 `protobuf:"varint,1,opt,name=magic" json:"magic,omitempty"`
	Allowed bool  `protobuf:"varint,2,opt,name=allowed" json:"allowed,omitempty"`
}

func (m *InitResponse) Reset()                    { *m = InitResponse{} }
func (m *InitResponse) String() string            { return proto.CompactTextString(m) }
func (*InitResponse) ProtoMessage()               {}
func (*InitResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InitResponse) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *InitResponse) GetAllowed() bool {
	if m != nil {
		return m.Allowed
	}
	return false
}

type Ping struct {
	Version int32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Magic   int32 `protobuf:"varint,2,opt,name=magic" json:"magic,omitempty"`
	Command int32 `protobuf:"varint,3,opt,name=command" json:"command,omitempty"`
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Ping) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Ping) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *Ping) GetCommand() int32 {
	if m != nil {
		return m.Command
	}
	return 0
}

type Command struct {
	Version   int32  `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Magic     int32  `protobuf:"varint,2,opt,name=magic" json:"magic,omitempty"`
	Command   int32  `protobuf:"varint,3,opt,name=command" json:"command,omitempty"`
	Argstring string `protobuf:"bytes,4,opt,name=argstring" json:"argstring,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Command) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Command) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *Command) GetCommand() int32 {
	if m != nil {
		return m.Command
	}
	return 0
}

func (m *Command) GetArgstring() string {
	if m != nil {
		return m.Argstring
	}
	return ""
}

func init() {
	proto.RegisterType((*Init)(nil), "messages.Init")
	proto.RegisterType((*InitResponse)(nil), "messages.InitResponse")
	proto.RegisterType((*Ping)(nil), "messages.Ping")
	proto.RegisterType((*Command)(nil), "messages.Command")
}

func init() { proto.RegisterFile("messages/messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x90, 0x3f, 0x6b, 0xc3, 0x30,
	0x14, 0xc4, 0x51, 0x6d, 0x57, 0xf6, 0xa3, 0x43, 0x11, 0x85, 0x6a, 0xe8, 0x60, 0x34, 0x79, 0x6a,
	0x86, 0xec, 0x59, 0xb2, 0x24, 0x9b, 0xd1, 0x37, 0x50, 0x6c, 0x21, 0x04, 0xd6, 0x9f, 0x48, 0x26,
	0xf9, 0xfa, 0xc1, 0x32, 0xc2, 0x59, 0x03, 0xd9, 0xee, 0x77, 0x70, 0xc7, 0xbd, 0x07, 0xbf, 0x46,
	0xc6, 0x28, 0x94, 0x8c, 0xbb, 0x2c, 0xfe, 0x7d, 0x70, 0xb3, 0x23, 0x75, 0x66, 0x76, 0x82, 0xf2,
	0x6c, 0xf5, 0x4c, 0x28, 0xe0, 0x9b, 0x0c, 0x51, 0x3b, 0x4b, 0x51, 0x8b, 0xba, 0x8a, 0x67, 0x24,
	0x3f, 0x50, 0x19, 0xa1, 0xf4, 0x40, 0x3f, 0x92, 0xbf, 0x02, 0xf9, 0x86, 0x42, 0x78, 0x4f, 0x8b,
	0x16, 0x75, 0x0d, 0x5f, 0x24, 0x3b, 0xc0, 0xd7, 0xd2, 0xc4, 0x65, 0xf4, 0xce, 0x46, 0xb9, 0xe5,
	0xd0, 0x73, 0x8e, 0x02, 0x16, 0xd3, 0xe4, 0xee, 0x72, 0x4c, 0x7d, 0x35, 0xcf, 0xc8, 0x7a, 0x28,
	0x7b, 0x6d, 0xd5, 0xcb, 0x4b, 0x28, 0xe0, 0xc1, 0x19, 0x23, 0xec, 0x98, 0xd6, 0x54, 0x3c, 0x23,
	0xbb, 0x02, 0x3e, 0xae, 0xf2, 0x7d, 0xa5, 0xe4, 0x0f, 0x1a, 0x11, 0x54, 0x9c, 0x83, 0xb6, 0x8a,
	0x96, 0xe9, 0xfc, 0xcd, 0xb8, 0x7c, 0xa6, 0xff, 0xee, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x69,
	0xb3, 0x96, 0x02, 0x7a, 0x01, 0x00, 0x00,
}
