// Code generated by protoc-gen-go.
// source: src/mainserver/config.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	src/mainserver/config.proto

It has these top-level messages:
	DateTime
	ConfigItem
	Config
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConfigType int32

const (
	ConfigType_InstalledApp ConfigType = 0
	ConfigType_Autostart    ConfigType = 1
)

var ConfigType_name = map[int32]string{
	0: "InstalledApp",
	1: "Autostart",
}
var ConfigType_value = map[string]int32{
	"InstalledApp": 0,
	"Autostart":    1,
}

func (x ConfigType) String() string {
	return proto.EnumName(ConfigType_name, int32(x))
}
func (ConfigType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DateTime struct {
	Year         uint32 `protobuf:"varint,1,opt,name=year" json:"year,omitempty"`
	Month        uint32 `protobuf:"varint,2,opt,name=month" json:"month,omitempty"`
	Day          uint32 `protobuf:"varint,3,opt,name=day" json:"day,omitempty"`
	Hour         uint32 `protobuf:"varint,4,opt,name=hour" json:"hour,omitempty"`
	Minute       uint32 `protobuf:"varint,5,opt,name=minute" json:"minute,omitempty"`
	Second       uint32 `protobuf:"varint,6,opt,name=second" json:"second,omitempty"`
	Milliseconds uint32 `protobuf:"varint,7,opt,name=milliseconds" json:"milliseconds,omitempty"`
}

func (m *DateTime) Reset()                    { *m = DateTime{} }
func (m *DateTime) String() string            { return proto.CompactTextString(m) }
func (*DateTime) ProtoMessage()               {}
func (*DateTime) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DateTime) GetYear() uint32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *DateTime) GetMonth() uint32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *DateTime) GetDay() uint32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *DateTime) GetHour() uint32 {
	if m != nil {
		return m.Hour
	}
	return 0
}

func (m *DateTime) GetMinute() uint32 {
	if m != nil {
		return m.Minute
	}
	return 0
}

func (m *DateTime) GetSecond() uint32 {
	if m != nil {
		return m.Second
	}
	return 0
}

func (m *DateTime) GetMilliseconds() uint32 {
	if m != nil {
		return m.Milliseconds
	}
	return 0
}

type ConfigItem struct {
	Type  ConfigType `protobuf:"varint,1,opt,name=type,enum=main.ConfigType" json:"type,omitempty"`
	Value string     `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *ConfigItem) Reset()                    { *m = ConfigItem{} }
func (m *ConfigItem) String() string            { return proto.CompactTextString(m) }
func (*ConfigItem) ProtoMessage()               {}
func (*ConfigItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ConfigItem) GetType() ConfigType {
	if m != nil {
		return m.Type
	}
	return ConfigType_InstalledApp
}

func (m *ConfigItem) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Config struct {
	Version   int32         `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Timestamp *DateTime     `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Item      []*ConfigItem `protobuf:"bytes,3,rep,name=item" json:"item,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Config) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Config) GetTimestamp() *DateTime {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Config) GetItem() []*ConfigItem {
	if m != nil {
		return m.Item
	}
	return nil
}

func init() {
	proto.RegisterType((*DateTime)(nil), "main.DateTime")
	proto.RegisterType((*ConfigItem)(nil), "main.ConfigItem")
	proto.RegisterType((*Config)(nil), "main.Config")
	proto.RegisterEnum("main.ConfigType", ConfigType_name, ConfigType_value)
}

func init() { proto.RegisterFile("src/mainserver/config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x51, 0xcd, 0x6a, 0xf3, 0x30,
	0x10, 0xfc, 0xfc, 0xd9, 0x71, 0x9a, 0xcd, 0x0f, 0x46, 0x94, 0x22, 0xe8, 0x25, 0x98, 0x1e, 0x42,
	0x69, 0x13, 0x48, 0x9f, 0x20, 0xb4, 0x87, 0xe6, 0x6a, 0xf2, 0x02, 0x6a, 0xb2, 0x6d, 0x04, 0x96,
	0x65, 0xa4, 0xb5, 0xc1, 0x2f, 0xd5, 0x67, 0x2c, 0x5a, 0x35, 0x94, 0xdc, 0x76, 0x66, 0x76, 0xa4,
	0x19, 0x09, 0xee, 0xbd, 0x3b, 0x6e, 0x8c, 0xd2, 0x8d, 0x47, 0xd7, 0xa3, 0xdb, 0x1c, 0x6d, 0xf3,
	0xa9, 0xbf, 0xd6, 0xad, 0xb3, 0x64, 0x45, 0x16, 0x84, 0xf2, 0x3b, 0x81, 0x9b, 0x37, 0x45, 0x78,
	0xd0, 0x06, 0x85, 0x80, 0x6c, 0x40, 0xe5, 0x64, 0xb2, 0x4c, 0x56, 0xf3, 0x8a, 0x67, 0x71, 0x0b,
	0x23, 0x63, 0x1b, 0x3a, 0xcb, 0xff, 0x4c, 0x46, 0x20, 0x0a, 0x48, 0x4f, 0x6a, 0x90, 0x29, 0x73,
	0x61, 0x0c, 0xde, 0xb3, 0xed, 0x9c, 0xcc, 0xa2, 0x37, 0xcc, 0xe2, 0x0e, 0x72, 0xa3, 0x9b, 0x8e,
	0x50, 0x8e, 0x98, 0xfd, 0x45, 0x81, 0xf7, 0x78, 0xb4, 0xcd, 0x49, 0xe6, 0x91, 0x8f, 0x48, 0x94,
	0x30, 0x33, 0xba, 0xae, 0x75, 0x84, 0x5e, 0x8e, 0x59, 0xbd, 0xe2, 0xca, 0x77, 0x80, 0x57, 0xae,
	0xb1, 0x27, 0x34, 0xe2, 0x01, 0x32, 0x1a, 0x5a, 0xe4, 0xc4, 0x8b, 0x6d, 0xb1, 0x0e, 0x9d, 0xd6,
	0x51, 0x3f, 0x0c, 0x2d, 0x56, 0xac, 0x86, 0x0e, 0xbd, 0xaa, 0x3b, 0xe4, 0x0e, 0x93, 0x2a, 0x82,
	0xb2, 0x87, 0x3c, 0x6e, 0x0a, 0x09, 0xe3, 0x1e, 0x9d, 0xd7, 0xb6, 0xe1, 0x83, 0x46, 0xd5, 0x05,
	0x8a, 0x27, 0x98, 0x90, 0x36, 0xe8, 0x49, 0x99, 0x96, 0xdd, 0xd3, 0xed, 0x22, 0x5e, 0x72, 0x79,
	0xb4, 0xea, 0x6f, 0x21, 0xa4, 0xd1, 0x84, 0x46, 0xa6, 0xcb, 0x74, 0x35, 0xbd, 0x4e, 0x13, 0xd2,
	0x56, 0xac, 0x3e, 0x3e, 0x5f, 0x1a, 0x84, 0x84, 0xa2, 0x80, 0xd9, 0xbe, 0xf1, 0xa4, 0xea, 0x1a,
	0x4f, 0xbb, 0xb6, 0x2d, 0xfe, 0x89, 0x39, 0x4c, 0x76, 0x1d, 0x59, 0x4f, 0xca, 0x51, 0x91, 0x7c,
	0xe4, 0xfc, 0x5d, 0x2f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x97, 0xd4, 0x25, 0x79, 0xcd, 0x01,
	0x00, 0x00,
}
